# Generated by Django 3.1.7 on 2021-04-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='short_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
